name: Deploy App to Server

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set Docker permissions
        run: |
          sudo chmod 666 /var/run/docker.sock
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:latest

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker stop apiContainer
            sudo docker rm apiContainer
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd
            sudo docker run -d -p 8000:8000 -e SERVERPORT=${{ secrets.SERVERPORT }} -e DBUSER=${{ secrets.DBUSER }} -e DBPASS=${{ secrets.DBPASS }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} --name apiContainer ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:latest
